apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: app
        image: yks0000/sample-service:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "100m"
            memory: 100Mi
          requests:
            cpu: "75m"
            memory: 75Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-metrics
  labels:
    metric: enabled
spec:
  type: NodePort
  selector:
    app: sample-service # Select the same pods as the main service
  ports:
  - protocol: TCP
    port: 8490
    targetPort: 8000 # The port your app exposes metrics on
