apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: app
        image: yks0000/sample-service:v2
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "100m"
            memory: 100Mi
          requests:
            cpu: "75m"
            memory: 75Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-metrics
  labels:
    metric: enabled
spec:
  type: NodePort
  selector:
    app: sample-service # Select the same pods as the main service
  ports:
  - protocol: TCP
    port: 8490
    targetPort: 8000 # The port your app exposes metrics on
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-service-hpa
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-service # Replace with the actual name of your deployment
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Object
    object:
      metric:
        name: namespace_west_app_container_avg_cpu_utilization
      describedObject:
        apiVersion: v1
        kind: Namespace
        name: cluster-west # Or the specific namespace you want to monitor
      target:
        type: Value # Or 'Value' depending on how the metric is reported
        value: "15"
  - type: Object
    object:
      metric:
        name: namespace_west_custom_synced_cpu_test_metric
      describedObject:
        apiVersion: v1
        kind: Namespace
        name: cluster-west # Or the specific namespace you want to monitor
      target:
        type: Value # Or 'Value' depending on how the metric is reported
        value: "2"